# Copyright (C) 2023 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a7y18lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin:system/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:system/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin:system/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000003e.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000003e.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000059.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000059.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000060.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000060.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/a7y18lte/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000045.drbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000045.drbin \
    vendor/samsung/a7y18lte/proprietary/vendor/bin/hw/vendor.trustonic.tee@1.0-service:system/vendor/bin/hw/vendor.trustonic.tee@1.0-service \
    vendor/samsung/a7y18lte/proprietary/vendor/bin/hw/vendor.trustonic.teeregistry@1.0-service:system/vendor/bin/hw/vendor.trustonic.teeregistry@1.0-service \
    vendor/samsung/a7y18lte/proprietary/vendor/bin/mcDriverDaemon:system/vendor/bin/mcDriverDaemon \
    vendor/samsung/a7y18lte/proprietary/vendor/etc/init/mobicore.rc:system/vendor/etc/init/mobicore.rc \
    vendor/samsung/a7y18lte/proprietary/vendor/etc/init/vendor.trustonic.tee@1.0-service.rc:system/vendor/etc/init/vendor.trustonic.tee@1.0-service.rc \
    vendor/samsung/a7y18lte/proprietary/vendor/etc/init/vendor.trustonic.teeregistry@1.0-service.rc:system/vendor/etc/init/vendor.trustonic.teeregistry@1.0-service.rc \
    vendor/samsung/a7y18lte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/a7y18lte/proprietary/vendor/firmware/fimc_is_rta.bin:system/vendor/firmware/fimc_is_rta.bin \
    vendor/samsung/a7y18lte/proprietary/vendor/firmware/setfile_4ha.bin:system/vendor/firmware/setfile_4ha.bin \
    vendor/samsung/a7y18lte/proprietary/vendor/firmware/setfile_5e9.bin:system/vendor/firmware/setfile_5e9.bin \
    vendor/samsung/a7y18lte/proprietary/vendor/firmware/setfile_imx576.bin:system/vendor/firmware/setfile_imx576.bin \
    vendor/samsung/a7y18lte/proprietary/vendor/firmware/setfile_imx576_front.bin:system/vendor/firmware/setfile_imx576_front.bin \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/hw/camera.exynos7885.so:system/vendor/lib/hw/camera.exynos7885.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/hw/gatekeeper.exynos7885.so:system/vendor/lib/hw/gatekeeper.exynos7885.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/hw/sensors.universal7885.so:system/vendor/lib/hw/sensors.universal7885.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libOpenCv.camera.samsung.so:system/vendor/lib/libOpenCv.camera.samsung.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libbauthserver.so:system/vendor/lib/libbauthserver.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libbauthtzcommon.so:system/vendor/lib/libbauthtzcommon.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libcsc.so:system/vendor/lib/libcsc.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libexynoscamera.so:system/vendor/lib/libexynoscamera.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libexynoscamera3.so:system/vendor/lib/libexynoscamera3.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libgiantmscl.so:system/vendor/lib/libgiantmscl.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libhifills.so:system/vendor/lib/libhifills.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libhifills_interface.so:system/vendor/lib/libhifills_interface.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libhigh_dynamic_range.so:system/vendor/lib/libhigh_dynamic_range.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libhwjpeg.so:system/vendor/lib/libhwjpeg.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libmfhdr_interface.so:system/vendor/lib/libmfhdr_interface.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libmpbase.so:system/vendor/lib/libmpbase.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libsaiv_BeautySolutionVideo.so:system/vendor/lib/libsaiv_BeautySolutionVideo.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libsensorlistener.so:system/vendor/lib/libsensorlistener.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libskeymaster3device.so:system/vendor/lib/libskeymaster3device.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libuniapi.so:system/vendor/lib/libuniapi.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libuniplugin.so:system/vendor/lib/libuniplugin.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/libvideobeauty_interface.so:system/vendor/lib/libvideobeauty_interface.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/vendor.trustonic.tee@1.0.so:system/vendor/lib/vendor.trustonic.tee@1.0.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib/vendor.trustonic.teeregistry@1.0.so:system/vendor/lib/vendor.trustonic.teeregistry@1.0.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/hw/camera.exynos7885.so:system/vendor/lib64/hw/camera.exynos7885.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/hw/gatekeeper.exynos7885.so:system/vendor/lib64/hw/gatekeeper.exynos7885.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/hw/keystore.mdfpp.so:system/vendor/lib64/hw/keystore.mdfpp.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/hw/sensors.universal7885.so:system/vendor/lib64/hw/sensors.universal7885.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libMcClient.so:system/vendor/lib64/libMcClient.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libOpenCv.camera.samsung.so:system/vendor/lib64/libOpenCv.camera.samsung.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libbauthserver.so:system/vendor/lib64/libbauthserver.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libbauthtzcommon.so:system/vendor/lib64/libbauthtzcommon.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libcsc.so:system/vendor/lib64/libcsc.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libexynoscamera.so:system/vendor/lib64/libexynoscamera.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libexynoscamera3.so:system/vendor/lib64/libexynoscamera3.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libgiantmscl.so:system/vendor/lib64/libgiantmscl.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libhifills.so:system/vendor/lib64/libhifills.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libhifills_interface.so:system/vendor/lib64/libhifills_interface.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libhigh_dynamic_range.so:system/vendor/lib64/libhigh_dynamic_range.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libhwjpeg.so:system/vendor/lib64/libhwjpeg.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libmfhdr_interface.so:system/vendor/lib64/libmfhdr_interface.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libmpbase.so:system/vendor/lib64/libmpbase.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libsaiv_BeautySolutionVideo.so:system/vendor/lib64/libsaiv_BeautySolutionVideo.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libsensorlistener.so:system/vendor/lib64/libsensorlistener.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libskeymaster3device.so:system/vendor/lib64/libskeymaster3device.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libuniapi.so:system/vendor/lib64/libuniapi.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libuniplugin.so:system/vendor/lib64/libuniplugin.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/libvideobeauty_interface.so:system/vendor/lib64/libvideobeauty_interface.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/vendor.trustonic.tee@1.0.so:system/vendor/lib64/vendor.trustonic.tee@1.0.so \
    vendor/samsung/a7y18lte/proprietary/vendor/lib64/vendor.trustonic.teeregistry@1.0.so:system/vendor/lib64/vendor.trustonic.teeregistry@1.0.so
